### ISSUE TITLE
No 'change' event firing for CAccordion/CAccordionItem when opened/closed

### ISSUE THREAD

**Issue by philwolstenholme** [chakra-ui/chakra-ui-vue#433] opened 2021-05-18 17:14 UTC
**Describe the bug**
The documentation (https://vue.chakra-ui.com/accordion#events) for the Accordion component lists a `change` event, but it does not seem to be firing (see attached devtools video). I wonder if this is linked to #412 ?

https://user-images.githubusercontent.com/6339853/118694256-cc7ba500-b803-11eb-8fa6-92da2a7d85de.mp4

**To Reproduce**
1. Add an Accordion & Accordion item(s) to a page
2. Attach a `@change` event OR use Vue Devtools to watch for events
3. Note that no `change` event is emitted

**Expected behavior**
A `change` event is emitted

**Screenshots**
https://user-images.githubusercontent.com/6339853/118694256-cc7ba500-b803-11eb-8fa6-92da2a7d85de.mp4

**Desktop (please complete the following information):**
 - Chrome 90.0.4430.212 on macOS

**Comment by peoray** [comment] 2021-05-23 23:57
Thank you for @philwolstenholme for reporting this issue. We'll take a look :)

**Comment by peoray** [comment] 2021-07-04 23:27
@philwolstenholme Can you confirm if this has been fixed? I just tried it and it worked. See [here](https://codesandbox.io/s/fragrant-cdn-4jmxn?file=/src/App.vue)

**Comment by peoray** [comment] 2021-07-20 03:07
Will be closing this for now since we can't reproduce the issue. Feel free to reopen if you encounter the issue again :)

**Closed by peoray** 2021-07-20 03:07 UTC
Labels: type: bug  🐛, type: contributions welcome 💚
